config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'category/show'
  root 'home#index'
  get 'home/index'
  devise_for :users
  resources :articles do
    member do
      post 'vote'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user, foreign_key: :author_id
  has_many :articles_categories, dependent: :destroy
  has_many :categories, through: :articles_categories
  has_many :votes, dependent: :destroy
  has_one_attached :article_image, dependent: :destroy

  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :text, presence: true, length: { minimum: 10, maximum: 500 }
  scope :desc, -> { order(created_at: :desc) }
end

app/models/articles_category.rb
class ArticlesCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles_categories
  has_many :articles, through: :articles_categories

  validates :name, presence: true, length: { minimum: 3, maximum: 10 }
  validates :priority, presence: true
  validates :priority, numericality: { only_integer: true }

  scope :prior, -> { order(priority: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles, foreign_key: :author_id
  validates :username, presence: true, uniqueness: true, length: { minimum: 3, maximum: 10 }
  validates :email, presence: true, uniqueness: true, length: { minimum: 4, maximum: 100 }
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :article

  validates :user_id, uniqueness: { scope: :article_id }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: %i[new edit]
  before_action :find_article, only: %i[show edit update destroy]

  def index
    @articles = Article.includes(:user).desc
  end

  def new
    @article = Article.new
    @categories = Category.all
  end

  def create
    @article = Article.new(article_params.merge(author_id: current_user.id))
    unless params[:article][:categories].nil?
      @category = Category.find(params[:article][:categories])
      @article.categories.push(@category)
    end
    if @article.save
      flash[:success] = 'Article Added'
      redirect_to root_path
    else
      flash[:error] = 'Article not Added'
      render 'new'
    end
  end

  def edit
    @categories = Category.all
    @selected_cat_ids = []
    @article.articles_categories.each { |c| @selected_cat_ids.push(c.category_id) }
  end

  def update
    @article.categories.destroy_all
    unless params[:article][:categories].nil?
      @category = Category.find(params[:article][:categories])
      @article.categories.push(@category)
    end
    if @article.update(article_params)
      flash[:success] = 'Article Updated'
      redirect_to @article
    else
      render 'edit'
    end
  end

  def show; end

  def destroy
    @article.destroy
    flash[:success] = 'Deleted Successfully'
    redirect_to root_path
  end

  def vote
    v = Vote.new(user_id: current_user.id, article_id: params[:id])
    if v.save
      flash[:success] = 'thums up'
    else
      flash[:error] = 'You already voted'
    end
    redirect_to article_path(params[:id])
  end

  private

  def find_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :text, :article_image)
  end
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.desc.includes(:user)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    featured_id = Vote.all.group(:article_id).count.map { |x, y| { id: x, count: y } }.max_by { |_k, v| v }
    featured_id = featured_id[:id] unless featured_id.nil?
    @feature_article = Article.find(featured_id) if featured_id.present?
    @categories = Category.prior
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def short_text(body)
    short_text = ''
    text_words = body.split(' ')
    5.times { |i| short_text = "#{short_text}#{text_words[i]} " unless text_words[i].nil? }
    short_text
  end

  def category_image(category)
    category.articles.last.article_image
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/form_helper.rb
module FormHelper
  def errors_for(form, field)
    content_tag(:p, form.object.errors[field].try(:first), class: 'help-block')
  end

  def form_group_for(form, field, opts = {}, &block)
    label = opts.fetch(:label, true)
    has_errors = form.object.errors[field].present?

    content_tag :div, class: "form-group #{'has-error' if has_errors}" do
      concat form.label(field, class: 'control-label') if label
      concat capture(&block)
      concat errors_for(form, field)
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/edit.html.erb
<%= form_with model: @article, class: 'form py-5 pl-5', id: 'article_form' do |f| %>
  <%= form_group_for f, :article_image, label: false  do %>
    <div class="input-group">
      <%= label_tag(:article_image, "Choose Image", class: 'ml-2 mt-2') %>
      <%= f.file_field :article_image, :class => 'mt-1 ml-1' %>
    </div>
  <% end %>

  <%= form_group_for f, :title, label: false  do %>
    <div class="input-group">
      <%= label_tag(:title, "Title", class: 'm-2') %>
      <%= f.text_field :title, class: 'form-control a-title-width', placeholder: 'Enter Article Title', autofocus: true %>
    </div>
  <% end %>

  <%= form_group_for f, :text, label: false  do %>
    <div class="input-group">
      <%= label_tag(:text, "Text", class: 'm-2') %>
      <%= f.text_area(:text ,size: "24x6", class: 'form-control a-article-width') %>
    </div>
  <% end %>
  <div class="ml-5">
  <% @categories.each do |category|  %>
    <% if @selected_cat_ids.any?(category.id) %>
      <%= check_box_tag 'article[categories][]', category.id, {checked: true} %>
    <% else %>
      <%= check_box_tag 'article[categories][]', category.id %>      
    <% end %>
    <span><%= category.name %></span>
  <% end %>
  </div>

  <div class="d-flex flex-row align-items-center pr-2">
    <%= f.submit "Edit Article", class: "btn btn-secondary mt-2 ml-5" %>
  </div>
<% end %>

app/views/articles/index.html.erb
<div class="row no-gutters mb-5">
  <% i = 0 %>
  <% @articles.in_groups_of(2, false) do |group| %>
    <% group.each do |article| %>
      <% if i.even? %>
        <div class="col-12 col-md-6">
          <div class="row no-gutters">
            <div class="col-12 col-md-6 bg-article" style="background: url(<%= url_for(article.article_image) %>)">
            </div>
            <div class="col-12 col-md-6">
              <span class="article-title font-weight-bold"><%= article.title%> </span>
              <br/>
              <span class="article-author"><%= article.user.username%></span> </span>
              <p class="article-detail"><%= short_text(article.text)  %></p>
              <%= link_to 'Read More', article_path(article.id), class: 'text-orange-hover read-more font-weight-bold' %>
            </div>
          </div>
        </div>
      <% else %>
        <div class="col-12 col-md-6">
          <div class="row no-gutters">
            <div class="col-12 col-md-6">
              <span class="article-title font-weight-bold"><%= article.title%> </span>
              <br/>
              <span class="article-author"><%= article.user.username%></span> </span>
              <p class="article-detail font-weight-bold"><%= short_text(article.text)  %></p>
              <%= link_to 'Read More', article_path(article.id), class: 'text-orange-hover read-more font-weight-bold' %>
            </div>
            <div class="col-12 col-md-6 bg-article" style="background: url(<%= url_for(article.article_image) %>)">

            </div>
          </div>
        </div>
      <% end %>
    <% end %>
    <% i = i+1 %>
  <% end %>
</div>

app/views/articles/new.html.erb
<%= form_with model: @article, class: 'form py-5 pl-5', id: 'article_form' do |f| %>
  <%= form_group_for f, :article_image, label: false  do %>
    <div class="input-group">
      <%= label_tag(:article_image, "Choose Image", class: 'ml-2 mt-2') %>
      <%= f.file_field :article_image, :class => 'mt-1 ml-1' %>
    </div>
  <% end %>

  <%= form_group_for f, :title, label: false  do %>
    <div class="input-group">
      <%= label_tag(:title, "Title", class: 'm-2') %>
      <%= f.text_field :title, class: 'form-control a-title-width', placeholder: 'Enter Article Title', autofocus: true %>
    </div>
  <% end %>

  <%= form_group_for f, :text, label: false  do %>
    <div class="input-group">
      <%= label_tag(:text, "Text", class: 'm-2') %>
      <%= f.text_area(:text ,size: "24x6", class: 'form-control a-article-width') %>
    </div>
  <% end %>
  <div class="ml-5">
 
  <% @categories.each do |category|  %>
    <%= check_box_tag 'article[categories][]', category.id %>
    <span><%= category.name %></span>
  <% end %>
  </div>

  <div class="d-flex flex-row align-items-center pr-2">
    <%= f.submit "Add Article", class: "btn btn-secondary mt-2 ml-5" %>
  </div>
<% end %>

app/views/articles/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h2 class="font-weight-bold mt-3 w-75"><%= @article.title%></h2>
      <%= image_tag(url_for(@article.article_image), alt: "Article Image", class: "main-image")%>
      <p class="w-75 article-detail ml-0 mt-3"><%= @article.text%></p>
      <div class="icon-links">
        <% if current_user %>
          <%= link_to vote_article_path(@article.id), method: :post,class: 'text-success mr-2' do %>
            <span class="vorder-round"> <%= @article.votes.count %> </span>
            <i class="fas fa-thumbs-up"></i>
          <% end %>
          <% if current_user.id == @article.author_id%>
            <%= link_to edit_article_path(@article.id), class: 'mr-2' do %>
              <i class="fas fa-edit"></i>
            <% end %>
            <%= link_to article_path(@article.id), method: :delete, class: 'text-danger' do %>
              <i class="fas fa-trash-alt"></i>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>  
</div>

app/views/category/show.html.erb
<h1 class="text-center mt-2"><%= @category.name %></h1>
<div class="row no-gutters">
  <% i = 0 %>
  <% @articles.in_groups_of(2, false) do |group| %>
    <% group.each do |article| %>
      <% if i.even? %>
        <div class="col-12 col-md-6">
          <div class="row no-gutters">
            <div class="col-12 col-md-6 bg-article" style="background: url(<%= url_for(article.article_image) %>)">
            </div>
            <div class="col-12 col-md-6">
              <h2 class="cat-show-tile"><%= @category.name%></h2>
              <span class="article-title font-weight-bold"><%= article.title%> </span>
              <br/>
              <span class="article-author"><%= article.user.username%></span> </span>
              <p class="article-detail"><%= short_text(article.text)  %></p>
              <%= link_to 'Read More', article_path(article.id), class: 'text-orange-hover read-more font-weight-bold' %>
            </div>
          </div>
        </div>
      <% else %>
        <div class="col-12 col-md-6">
          <div class="row no-gutters">
            <div class="col-12 col-md-6">
              <h2 class="cat-show-tile"><%= @category.name%></h2>
              <span class="article-title font-weight-bold"><%= article.title%> </span>
              <br/>
              <span class="article-author"><%= article.user.username%></span> </span>
              
              <p class="article-detail font-weight-bold"><%= short_text(article.text)  %></p>
              <%= link_to 'Read More', article_path(article.id), class: 'text-orange-hover read-more font-weight-bold' %>
            </div>
            <div class="col-12 col-md-6 bg-article" style="background: url(<%= url_for(article.article_image) %>)">

            </div>
          </div>
        </div>
      <% end %>
    <% end %>
    <% i = i+1 %>
  <% end %>
</div>

app/views/home/index.html.erb
<section class="feature-article" id="feature-article" style="background: url(<%= url_for(@feature_article.article_image)%>); background-repeat: no-repeat; background-size:cover;">
  <%= link_to article_path(@feature_article.id) do %>
    <div class="overlay"></div>
    <div class = "lower-text">
      <span class="title">
        <%=@feature_article.title %>
      </span>
      <br/>
      <span class="text-white">
        <%= short_text(@feature_article.text)  %>
      </span>
      <br/>
      <span class="text-white">
        <%= @feature_article.created_at %>
      </span>
    </div>
  <% end %>
</section>
<section id="categories">
  <div class="row no-gutters">
    <% @categories.each  do |category| %>
      <div class="col-12 col-md-3">
        <%= link_to category_show_path('id' => category.id), :class => 'button white' do %>
          <div class="category" style="background: url(<%= url_for(category_image(category))%>); background-size:cover !important ">
            <span class="category-title"><%= category.name %></span>
            <span class="category-text"><%= category.articles.last.title %></span>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LifestyleArticles</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css"
    />
  </head>

  <body>
    <%= render :partial => 'shared/flash_messages', :flash => flash %>
    <%= render 'shared/navbar'%>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% if flash.present? %>
  <div id='flash'>
   <script>
     <% if flash[:success] %>
       var $toastContent = $('<span><%= flash[:success] %></span>');
       toastr.success($toastContent)
     <% end %>
     <% if flash[:info] %>
       var $toastContent = $('<span><%= flash[:info] %></span>');
       toastr.info($toastContent)
     <% end %>
     <% if flash[:danger] %>
       var $toastContent = $('<span><%= flash[:danger] %></span>');
       toastr.error($toastContent)
     <% end %>
     <% if flash[:error] %>
       var $toastContent = $('<span><%= flash[:error] %></span>');
       toastr.error($toastContent)
     <% end %>
   </script>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<section id="footer" class="fixed-bottom bg-dark footer">
  <div class="row no-gutters">
    <div class="col-md-3">
      <a class="navbar-brand ml-3 font-weight-bold text-white" href="#">People's Style</a>
    </div>
    <div class="col-md-6 d-flex align-items-center copy">
      <a class="text-orange text-orange-hover" href="#">Privacy Policy</a>
      <a class="text-orange text-orange-hover" href="#">Terms & Conditions</a>
      <span class="text-white">Copyright 2020 All rights reserved </span>
    </div>
    <div class="col-md-3 d-flex align-items-center social-icons">
      <a href='https://github.com/talhawaqar' class="text-white ">
        <i class="fab fa-github text-orange-hover"></i>
      </a>
      <a href='https://www.linkedin.com/in/talhawaqar/' class="text-white">
        <i class="fab fa-linkedin-in text-orange-hover"></i>
      </a>
      <a href='https://twitter.com/MuhammadTalhaW4' class="text-white">
        <i class="fab fa-twitter text-orange-hover"></i>
      </a>
    </div>
  </div>
</section>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light d-flex">
  <div class="w-25">
    <%= link_to 'People\'s Style', root_path, class: 'navbar-brand'%>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
  
  <div class="collapse navbar-collapse d-flex justify-content-between" id="navbarSupportedContent">
    <div class="align-self-center">
      <ul class="navbar-nav text-uppercase">
        <li class="nav-item">
          <%= link_to "All", articles_path, class: 'nav-link text-orange-hover' %>
        </li>
        <% Category.all.each do |category| %>
          <li class="nav-item">
            <%= link_to category.name, category_show_path('id' => category.id), class: 'nav-link text-orange-hover' %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to 'Write Article', new_article_path, class: 'nav-link text-orange-hover' %>
        </li>
      </ul>
    </div>
    <div class="">
      <ul class="navbar-nav">
        <% if current_user %>
          <li class="nav-item ">
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item ">
            <%= link_to 'Sign in', user_session_path, class: 'nav-link border-right' %>
          </li>
           <li class="nav-item ">
            <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>